name: openmodes
channels:
  - conda-forge
dependencies:
  - python>3.8
  - pip
  - numpy
  - compilers
  - gmsh >= 3.0.0
  - numpy >= 1.22
  - scipy >= 0.18.0
  - matplotlib
  - jinja2
  - six
  - ipywidgets
  - meshio
  - dill
  - pyvista
  - mayavi
