!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitconstants(f2pysetupfunc)
      use constants, only : wp
      use constants, only : dp
      use constants, only : sp
      external f2pysetupfunc
      call f2pysetupfunc(wp,dp,sp)
      end subroutine f2pyinitconstants

      
      subroutine f2pyinitcore_for(f2pysetupfunc)
      use core_for, only : c
      use core_for, only : pi
      external f2pysetupfunc
      call f2pysetupfunc(c,pi)
      end subroutine f2pyinitcore_for


